### ISSUE TITLE
Cannot find chat secret on dashboard

### ISSUE THREAD

**Issue by RajChanchal** [edwellbrook/gosquared-swift#3]
To add chat module into iOS, needed a secret key. But there seems to be no documentation that specifiy how can we can a secret key string to let ios chat box connection

**Comment by edwellbrook** [comment]
Hey Raj, this library is for working with the GoSquared API. If you're looking to use the chat SDK please see the official project here: https://github.com/edwellbrook/gosquared-swift/issues/3
